const SB_URL='https://jxomjwyhxdjjjwquddkl.supabase.co';
const SB_KEY='sb_publishable_iRWDkRc72rVXfqsj9T3_Hg_bGARpRBw';
const sb=window.supabase.createClient(SB_URL,SB_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtSec=s=>{s=Math.max(0,Math.floor(s||0));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
const levelText=v=>({auto:'Automático',level1:'Nível 1 • Fundamentos',level2:'Nível 2 • Intermediário',level3:'Nível 3 • Avançado',challenge:'Desafio • Avançado+'})[v]||'Automático';
const SESSION_KEY='mcmV15CurrentQuiz', PENDING_KEY='mcmV15PendingAnswers';
let authSession=null,member=null,catalog=[],bankStats=null;
let quiz={questions:[],index:0,mode:null,label:null,startedAt:0,qStartedAt:0,hits:0,answers:[],examMeta:null,revealEach:true};
let tick=null;
let deviceId=localStorage.getItem('mcmDeviceId');if(!deviceId){deviceId=crypto.randomUUID();localStorage.setItem('mcmDeviceId',deviceId)}

function msg(el,type,text){el.innerHTML=`<div class="${type==='bad'?'bad-box':type==='ok'?'ok-box':'warn-box'}">${esc(text)}</div>`}
function setView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===name));const v=$(`view-${name}`);if(v)v.classList.add('active-view');if(name==='progress')loadProgress();if(name==='exams')renderCatalog();window.scrollTo({top:0,behavior:'smooth'});}
function bindNav(){document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',()=>setView(el.dataset.view)));}

async function studentLogin(){const u=$('studentUser').value.trim().toLowerCase(),p=$('studentPass').value;if(!u||!p)return msg($('loginMsg'),'bad','Informe usuário e senha.');$('studentLoginBtn').disabled=true;msg($('loginMsg'),'warn','Entrando…');try{const r=await fetch(`${SB_URL}/functions/v1/student-login`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SB_KEY},body:JSON.stringify({username:u,password:p})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha no login');const {data,error}=await sb.auth.setSession({access_token:j.access_token,refresh_token:j.refresh_token});if(error)throw error;await boot(data.session)}catch(e){msg($('loginMsg'),'bad',e.message)}finally{$('studentLoginBtn').disabled=false}}

async function boot(s){authSession=s;if(!s){$('loginCard').classList.remove('hide');$('studentApp').classList.add('hide');$('logoutBtn').classList.add('hide');$('cloudState').textContent='Não autenticado';return}const {data:m,error}=await sb.from('family_members').select('family_id,user_id,role,display_name,username').eq('user_id',s.user.id).maybeSingle();if(error||!m||m.role!=='student'){await sb.auth.signOut();msg($('loginMsg'),'warn','Esta versão é o ambiente do aluno. Use o painel dos responsáveis para a conta do responsável.');return}member=m;$('loginCard').classList.add('hide');$('studentApp').classList.remove('hide');$('logoutBtn').classList.remove('hide');$('cloudState').textContent='☁️ Sincronizado';$('studentName').textContent=m.display_name;await Promise.all([loadDashboard(),loadBank(),flushPending()]);restoreQuiz();}

async function loadDashboard(){const uid=member.user_id;const [{count:total},{count:real},{count:realCorrect},{data:set}]=await Promise.all([
 sb.from('answers').select('*',{count:'exact',head:true}).eq('student_user_id',uid),
 sb.from('answers').select('*',{count:'exact',head:true}).eq('student_user_id',uid).like('question_key','real:%'),
 sb.from('answers').select('*',{count:'exact',head:true}).eq('student_user_id',uid).like('question_key','real:%').eq('is_correct',true),
 sb.from('student_settings').select('question_level').eq('student_user_id',uid).maybeSingle()
]);$('totalN').textContent=total||0;$('realN').textContent=real||0;$('realPct').textContent=real?`${Math.round((realCorrect||0)*100/real)}%`:'0%';$('levelLabel').textContent=`Nível das questões: ${levelText(set?.question_level||'auto')}`;}

async function loadBank(){const [{data:stats,error:se},{data:cat,error:ce}]=await Promise.all([sb.rpc('get_real_bank_stats'),sb.rpc('get_real_exam_catalog')]);if(se)throw se;if(ce)throw ce;bankStats=stats?.[0]||null;catalog=cat||[];if(bankStats){$('bankCatalogued').textContent=bankStats.catalogued_questions;$('bankReady').textContent=bankStats.ready_questions;$('bankExamCount').textContent=bankStats.catalogued_exams;$('libCatalogued').textContent=bankStats.catalogued_questions;$('libReady').textContent=bankStats.ready_questions;$('libExams').textContent=bankStats.catalogued_exams;$('libInstitutions').textContent=bankStats.institutions;}const {count:seen}=await sb.from('real_question_exposures').select('*',{count:'exact',head:true}).eq('student_user_id',member.user_id);$('unseenReady').textContent=Math.max(0,Number(bankStats?.ready_questions||0)-Number(seen||0));renderCatalog();renderLibrarySummary();}

function renderCatalog(){if(!$('examCatalog'))return;const q=($('examSearch').value||'').toLowerCase(),status=$('examStatus').value;const items=catalog.filter(x=>{const text=`${x.institution} ${x.exam_year}`.toLowerCase();const st=status==='all'||(status==='ready'&&x.has_complete_ready_exam)||(status==='processing'&&!x.has_complete_ready_exam);return text.includes(q)&&st});$('examCatalog').innerHTML=items.length?items.map((x,i)=>{const pct=x.catalogued_questions?Math.round(x.ready_questions*100/x.catalogued_questions):0;const ready=x.has_complete_ready_exam;return `<article class="exam-card"><div class="exam-card-head"><div><h3>${esc(x.institution)}</h3><div class="exam-meta">${esc(x.exam_year)} • ${esc(x.subjects||'')}</div></div><span class="pill">${ready?'✅ Completa':`⏳ ${x.ready_questions}/${x.catalogued_questions}`}</span></div><div class="exam-progress"><div class="bar"><i style="width:${pct}%"></i></div><b>${pct}%</b></div><div class="actions"><button class="btn ${ready?'primary':'secondary'} exam-start" data-inst="${esc(x.institution)}" data-year="${esc(x.exam_year)}" data-complete="${ready}">${ready?'Fazer prova completa':`Abrir ${x.ready_questions} questões prontas`}</button></div></article>`}).join(''):'<div class="info-box">Nenhuma prova encontrada com esse filtro.</div>';document.querySelectorAll('.exam-start').forEach(b=>b.onclick=()=>startExam(b.dataset.inst,b.dataset.year,b.dataset.complete==='true'));}

function renderLibrarySummary(){const m=new Map();catalog.forEach(x=>{const a=m.get(x.institution)||{catalogued:0,ready:0,years:0};a.catalogued+=Number(x.catalogued_questions||0);a.ready+=Number(x.ready_questions||0);a.years++;m.set(x.institution,a)});$('librarySummary').innerHTML=[...m.entries()].map(([k,v])=>`<div class="school-row"><div><b>${esc(k)}</b><div class="muted">${v.years} provas/anos catalogados</div></div><div><b>${v.ready}/${v.catalogued}</b><div class="muted">prontas</div></div></div>`).join('');}

async function startReal(mode){const review=mode==='revisao_real',subject=$(review?'reviewSubject':'trainSubject').value||null,limit=Number($(review?'reviewAmount':'trainAmount').value),box=$(review?'reviewMsg':'trainMsg'),btn=$(review?'startReviewBtn':'startRealBtn');btn.disabled=true;msg(box,'warn','Selecionando questões reais inéditas…');try{const {data,error}=await sb.rpc('get_my_real_question_set',{p_subject:subject,p_limit:limit,p_mode:mode});if(error)throw error;if(!data?.length)throw new Error('Não há questões inéditas prontas para esse filtro. Tente outra matéria ou consulte as provas anteriores.');beginQuiz(data,mode,review?'Revisão inteligente':'Treino real',true,null);box.innerHTML=''}catch(e){msg(box,'bad',e.message)}finally{btn.disabled=false}}

async function startExam(inst,year,complete){try{const {data,error}=await sb.rpc('get_my_complete_real_exam',{p_institution:inst,p_exam_year:year});if(error)throw error;if(!data?.length)throw new Error('Essa prova ainda não possui questões prontas para execução.');beginQuiz(data,'prova_real',complete?'Prova completa':'Questões prontas da prova',false,{institution:inst,year,complete});}catch(e){alert(e.message)}}

function beginQuiz(data,mode,label,revealEach,examMeta){quiz={questions:data,index:0,mode,label,startedAt:Date.now(),qStartedAt:Date.now(),hits:0,answers:[],examMeta,revealEach};persistQuiz();$('resultCard').classList.add('hide');$('quizCard').classList.remove('hide');renderQuestion();startTick();$('quizCard').scrollIntoView({behavior:'smooth',block:'start'});}

function persistQuiz(){if(quiz.questions?.length)localStorage.setItem(SESSION_KEY,JSON.stringify(quiz));else localStorage.removeItem(SESSION_KEY)}
function restoreQuiz(){try{const raw=localStorage.getItem(SESSION_KEY);if(!raw)return;const q=JSON.parse(raw);if(!q.questions?.length||q.index>=q.questions.length)return localStorage.removeItem(SESSION_KEY);quiz=q;quiz.qStartedAt=Date.now();$('quizCard').classList.remove('hide');renderQuestion();startTick();}catch{localStorage.removeItem(SESSION_KEY)}}
function startTick(){clearInterval(tick);tick=setInterval(()=>{if(!quiz.questions.length)return;$('questionTimer').textContent=fmtSec((Date.now()-quiz.qStartedAt)/1000);$('totalTimer').textContent=`Total ${fmtSec((Date.now()-quiz.startedAt)/1000)}`},1000)}

function renderQuestion(){const q=quiz.questions[quiz.index];const n=quiz.index+1,total=quiz.questions.length;$('quizMode').textContent=quiz.label.toUpperCase();$('quizTitle').textContent=`Questão ${n} de ${total}`;$('quizProgress').style.width=`${Math.round(n*100/total)}%`;$('answerFeedback').innerHTML='';$('nextQuestionBtn').disabled=false;$('nextQuestionBtn').textContent='Confirmar resposta';const source=`${q.institution} • ${q.exam_year} • ${q.subject} • Q${q.question_no}`;const context=q.context_text?`<div class="context-box">${q.context_label?`<b>${esc(q.context_label)}</b><br>`:''}${esc(q.context_text)}</div>`:'';$('questionStage').innerHTML=`<div class="question-source"><span class="source-tag">QUESTÃO REAL</span><span class="source-tag">${esc(source)}</span>${q.topic?`<span class="source-tag">${esc(q.topic)}</span>`:''}</div>${context}<div class="question-text">${esc(q.exact_text)}</div><div class="options">${(q.options||[]).map((o,i)=>`<label class="option"><input type="radio" name="realAnswer" value="${i}"><span><span class="option-letter">${String.fromCharCode(65+i)})</span> ${esc(o)}</span></label>`).join('')}</div>`;document.querySelectorAll('.option input').forEach(x=>x.onchange=()=>{document.querySelectorAll('.option').forEach(o=>o.classList.remove('chosen'));x.closest('.option').classList.add('chosen')});quiz.qStartedAt=Date.now();persistQuiz();}

async function confirmAnswer(){const q=quiz.questions[quiz.index],picked=document.querySelector('input[name="realAnswer"]:checked');if(!picked)return msg($('answerFeedback'),'bad','Escolha uma alternativa antes de continuar.');$('nextQuestionBtn').disabled=true;const selected=Number(picked.value),ok=selected===q.correct_index,elapsed=Math.max(1,Math.round((Date.now()-quiz.qStartedAt)/1000));if(ok)quiz.hits++;const rec={questionId:q.id,subject:q.subject,topic:q.topic,selected,correct:q.correct_index,ok,elapsed,source:{institution:q.institution,year:q.exam_year,questionNo:q.question_no,examId:q.exam_id}};quiz.answers.push(rec);await saveAnswer(q,rec);persistQuiz();if(quiz.revealEach){$('answerFeedback').innerHTML=`<div class="${ok?'ok-box':'bad-box'}"><b>${ok?'✅ Correto':'❌ Incorreto'}</b><br>Resposta correta: <b>${String.fromCharCode(65+q.correct_index)}) ${esc(q.options[q.correct_index])}</b><br><span class="muted">Fonte: ${esc(q.institution)} • ${esc(q.exam_year)} • questão ${q.question_no}</span></div>`;$('nextQuestionBtn').disabled=false;$('nextQuestionBtn').textContent=quiz.index===quiz.questions.length-1?'Ver resultado':'Próxima questão';$('nextQuestionBtn').onclick=advanceQuestion;}else{advanceQuestion()}}

function advanceQuestion(){quiz.index++;if(quiz.index>=quiz.questions.length)return finishQuiz();renderQuestion();$('nextQuestionBtn').onclick=confirmAnswer;}

async function saveAnswer(q,a){const mode=quiz.mode==='revisao_real'?'revisao':quiz.mode==='prova_real'?'simulado':'treino';const row={family_id:member.family_id,student_user_id:member.user_id,question_key:`real:${q.id}`,subject:q.subject,topic:q.topic||null,difficulty:null,mode,is_correct:a.ok,selected_answer:String(q.options[a.selected]??''),correct_answer:String(q.options[q.correct_index]??''),elapsed_seconds:a.elapsed,question_source:{source_type:'official_exact',institution:q.institution,exam_year:q.exam_year,question_no:q.question_no,exam_id:q.exam_id,real_question_id:q.id},answered_at:new Date().toISOString(),client_event_id:crypto.randomUUID(),device_id:deviceId};const {error}=await sb.from('answers').insert(row);if(error)queuePending(row);}
function queuePending(row){const a=JSON.parse(localStorage.getItem(PENDING_KEY)||'[]');a.push(row);localStorage.setItem(PENDING_KEY,JSON.stringify(a))}
async function flushPending(){const a=JSON.parse(localStorage.getItem(PENDING_KEY)||'[]');if(!a.length)return;const keep=[];for(const row of a){const {error}=await sb.from('answers').insert(row);if(error)keep.push(row)}if(keep.length)localStorage.setItem(PENDING_KEY,JSON.stringify(keep));else localStorage.removeItem(PENDING_KEY)}

async function finishQuiz(){clearInterval(tick);const elapsed=Math.max(1,Math.round((Date.now()-quiz.startedAt)/1000)),total=quiz.questions.length,hits=quiz.hits;const mode=quiz.mode==='revisao_real'?'revisao':quiz.mode==='prova_real'?'simulado':'treino';await sb.from('study_sessions').insert({family_id:member.family_id,student_user_id:member.user_id,mode,correct_count:hits,total_count:total,total_seconds:elapsed,avg_seconds:Math.round(elapsed/total),started_at:new Date(quiz.startedAt).toISOString(),finished_at:new Date().toISOString(),client_session_id:crypto.randomUUID(),device_id:deviceId});const details=quiz.revealEach?'':quiz.answers.map((a,i)=>{const q=quiz.questions[i];return `<div class="answer-row"><b>${a.ok?'✅':'❌'} ${esc(q.subject)} • ${esc(q.institution)} ${esc(q.exam_year)} • Q${q.question_no}</b><span>Sua resposta: ${String.fromCharCode(65+a.selected)} • Correta: ${String.fromCharCode(65+a.correct)}</span></div>`}).join('');$('quizCard').classList.add('hide');$('resultCard').classList.remove('hide');$('resultCard').innerHTML=`<div class="result-score"><span>Resultado</span><strong>${hits}/${total}</strong><span>${Math.round(hits*100/total)}% • ${fmtSec(elapsed)}</span></div>${details}<div class="actions"><button class="btn primary" id="newBlockBtn">Novo treino real</button><button class="btn secondary" id="progressBtn">Ver desempenho</button></div>`;$('newBlockBtn').onclick=()=>setView('train');$('progressBtn').onclick=()=>setView('progress');quiz={questions:[],index:0,mode:null,label:null,startedAt:0,qStartedAt:0,hits:0,answers:[],examMeta:null,revealEach:true};persistQuiz();await Promise.all([loadDashboard(),loadBank(),loadProgress()]);$('resultCard').scrollIntoView({behavior:'smooth',block:'start'});}

function quitQuiz(){if(!quiz.questions.length)return;if(confirm('Sair deste bloco? As questões já exibidas continuarão marcadas como vistas para evitar repetição.')){clearInterval(tick);quiz={questions:[],answers:[]};persistQuiz();$('quizCard').classList.add('hide');setView('home')}}

async function loadProgress(){if(!member)return;const {data,error}=await sb.from('answers').select('question_key,subject,topic,is_correct,elapsed_seconds,answered_at,question_source').eq('student_user_id',member.user_id).like('question_key','real:%').order('answered_at',{ascending:false}).limit(500);if(error)return;const a=data||[],correct=a.filter(x=>x.is_correct).length,wrong=a.length-correct,timed=a.filter(x=>Number.isFinite(x.elapsed_seconds));$('pCorrect').textContent=correct;$('pWrong').textContent=wrong;$('pTime').textContent=timed.length?`${Math.round(timed.reduce((s,x)=>s+x.elapsed_seconds,0)/timed.length)}s`:'—';$('pUnique').textContent=new Set(a.map(x=>x.question_key)).size;const subjects=['Matemática','Português'];$('subjectBars').innerHTML=subjects.map(s=>{const x=a.filter(r=>r.subject===s),h=x.filter(r=>r.is_correct).length,p=x.length?Math.round(h*100/x.length):0;return `<div class="subject-block"><div class="subject-line"><b>${s}</b><span>${h}/${x.length} • ${p}%</span></div><div class="bar"><i style="width:${p}%"></i></div></div>`}).join('');const errs=a.filter(x=>!x.is_correct).slice(0,6);$('recentErrors').innerHTML=errs.length?errs.map(x=>`<div class="answer-row"><b>${esc(x.subject||'Questão real')} • ${esc(x.question_source?.institution||'')}</b><span>${esc(x.question_source?.exam_year||'')} • questão ${esc(x.question_source?.question_no||'')} • ${new Date(x.answered_at).toLocaleDateString('pt-BR')}</span></div>`).join(''):'<div class="info-box">Nenhum erro real registrado ainda.</div>';}

$('studentLoginBtn').onclick=studentLogin;$('startRealBtn').onclick=()=>startReal('treino_real');$('startReviewBtn').onclick=()=>startReal('revisao_real');$('nextQuestionBtn').onclick=confirmAnswer;$('quitQuizBtn').onclick=quitQuiz;$('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};$('parentBtn').onclick=()=>location.href='../missao-colegio-militar-v13/?from=v15';$('examSearch').oninput=renderCatalog;$('examStatus').onchange=renderCatalog;window.addEventListener('online',flushPending);bindNav();sb.auth.getSession().then(({data})=>boot(data.session));
