const $=id=>document.getElementById(id),STORE='mcmV06';
const REW=[{n:10,name:'Sorvete',emoji:'🍦'},{n:20,name:'Milk-shake',emoji:'🥤'},{n:30,name:'Prêmio surpresa',emoji:'🎁'}];
const Q=[
{id:1,g:1,s:'Matemática',t:'Operações',d:1,q:'Quanto é 360 ÷ 12?',a:['20','25','30','35'],c:2,e:'12 × 30 = 360, logo 360 ÷ 12 = 30.'},
{id:2,g:1,s:'Matemática',t:'Frações',d:2,q:'Qual é 1/2 + 1/4?',a:['1/4','2/4','3/4','1'],c:2,e:'1/2 equivale a 2/4. Então 2/4 + 1/4 = 3/4.'},
{id:3,g:1,s:'Matemática',t:'Geometria',d:1,q:'Um quadrado de lado 7 m tem área de:',a:['14 m²','28 m²','42 m²','49 m²'],c:3,e:'Área do quadrado = lado × lado = 7 × 7 = 49 m².'},
{id:4,g:1,s:'Matemática',t:'Medidas',d:1,q:'2,5 litros equivalem a:',a:['250 mL','2.500 mL','25.000 mL','250.000 mL'],c:1,e:'1 L = 1.000 mL. Portanto, 2,5 L = 2.500 mL.'},
{id:5,g:1,s:'Matemática',t:'Sequências',d:2,q:'3, 6, 12, 24, __',a:['30','36','42','48'],c:3,e:'Cada termo é o dobro do anterior: 24 × 2 = 48.'},
{id:6,g:1,s:'Matemática',t:'Porcentagem',d:2,q:'10% de R$ 120 é:',a:['R$ 10','R$ 12','R$ 20','R$ 22'],c:1,e:'10% é a décima parte: 120 ÷ 10 = 12.'},
{id:7,g:1,s:'Matemática',t:'Problemas',d:2,q:'4 cadernos custam R$ 28. Quanto custa 1?',a:['R$ 5','R$ 6','R$ 7','R$ 8'],c:2,e:'28 ÷ 4 = 7 reais por caderno.'},
{id:8,g:1,s:'Matemática',t:'Tempo',d:2,q:'Uma prova começou às 13h40 e terminou às 16h15. Quanto durou?',a:['2h15','2h25','2h35','2h45'],c:2,e:'De 13h40 a 16h15 passam 2h35.'},
{id:9,g:1,s:'Matemática',t:'Decimais',d:2,q:'Quanto é 5,7 + 2,35?',a:['7,95','8,05','8,15','8,25'],c:1,e:'5,70 + 2,35 = 8,05.'},
{id:10,g:1,s:'Matemática',t:'Raciocínio',d:3,q:'Se cada caixa tem 24 lápis, quantos há em 5 caixas?',a:['96','100','110','120'],c:3,e:'5 × 24 = 120.'},
{id:11,g:1,s:'Português',t:'Ortografia',d:1,q:'Assinale a palavra correta.',a:['Excessão','Exceção','Exessão','Eseção'],c:1,e:'A grafia correta é “exceção”.'},
{id:12,g:1,s:'Português',t:'Classes gramaticais',d:1,q:'Em “A menina curiosa abriu o livro”, “curiosa” é:',a:['verbo','substantivo','adjetivo','pronome'],c:2,e:'“Curiosa” caracteriza “menina”; portanto é adjetivo.'},
{id:13,g:1,s:'Português',t:'Verbos',d:1,q:'Em “Nós estudaremos amanhã”, o verbo indica:',a:['passado','presente','futuro','ordem'],c:2,e:'“Estudaremos” indica ação futura.'},
{id:14,g:1,s:'Português',t:'Pontuação',d:2,q:'Qual frase está correta?',a:['Maria venha aqui.','Maria, venha aqui.','Maria venha, aqui.','Maria; venha aqui.'],c:1,e:'“Maria” é vocativo e deve ser separado por vírgula.'},
{id:15,g:1,s:'Português',t:'Vocabulário',d:1,q:'“Exausto” significa:',a:['distraído','cansado','animado','curioso'],c:1,e:'Exausto significa muito cansado.'},
{id:16,g:1,s:'Português',t:'Interpretação',d:2,q:'“Ao ver nuvens escuras, Paulo recolheu as roupas do varal.” Ele provavelmente esperava:',a:['sol','chuva','visita','calor'],c:1,e:'As nuvens escuras e a retirada das roupas indicam possibilidade de chuva.'},
{id:17,g:1,s:'Português',t:'Pronomes',d:2,q:'Em “Ana encontrou Paula e entregou-lhe o caderno”, “lhe” refere-se a:',a:['Ana','Paula','caderno','ninguém'],c:1,e:'“Lhe” retoma Paula, que recebe o caderno.'},
{id:18,g:1,s:'Português',t:'Concordância',d:2,q:'Assinale a frase correta.',a:['As menina estudou.','Os aluno chegaram.','As crianças brincaram.','A professores explicou.'],c:2,e:'“As crianças brincaram” apresenta concordância correta.'},
{id:19,g:1,s:'Português',t:'Coesão',d:3,q:'“Estudou bastante; _____, melhorou o resultado.”',a:['porém','portanto','embora','enquanto'],c:1,e:'“Portanto” introduz uma conclusão.'},
{id:20,g:1,s:'Português',t:'Interpretação',d:3,q:'“A biblioteca estava cheia e silenciosa. Cada aluno parecia mergulhado em seu próprio universo.” Isso sugere que estavam:',a:['conversando','concentrados','esperando','saindo'],c:1,e:'A expressão sugere concentração intensa.'},
{id:21,s:'Matemática',t:'Operações',d:1,q:'Quanto é 480 ÷ 16?',a:['20','25','30','35'],c:2,e:'16 × 30 = 480.'},
{id:22,s:'Matemática',t:'Operações',d:1,q:'Quanto é 27 × 14?',a:['368','378','388','398'],c:1,e:'27 × 14 = 270 + 108 = 378.'},
{id:23,s:'Matemática',t:'Frações',d:1,q:'Qual fração equivale a 1/2?',a:['2/3','2/4','3/4','4/5'],c:1,e:'1/2 = 2/4.'},
{id:24,s:'Matemática',t:'Frações',d:2,q:'Quanto é 3/5 - 1/5?',a:['1/5','2/5','2/10','3/10'],c:1,e:'Com denominadores iguais: 3 - 1 = 2, então 2/5.'},
{id:25,s:'Matemática',t:'Frações',d:3,q:'Quanto é 2/3 de 24?',a:['8','12','16','18'],c:2,e:'24 ÷ 3 = 8; 8 × 2 = 16.'},
{id:26,s:'Matemática',t:'Geometria',d:1,q:'Um retângulo mede 9 cm por 4 cm. Seu perímetro é:',a:['13','26','36','45'],c:1,e:'9 + 4 + 9 + 4 = 26 cm.'},
{id:27,s:'Matemática',t:'Geometria',d:2,q:'Um retângulo mede 12 m por 5 m. Sua área é:',a:['17','34','60','120'],c:2,e:'12 × 5 = 60 m².'},
{id:28,s:'Matemática',t:'Medidas',d:1,q:'3 km correspondem a:',a:['30 m','300 m','3.000 m','30.000 m'],c:2,e:'1 km = 1.000 m; 3 km = 3.000 m.'},
{id:29,s:'Matemática',t:'Medidas',d:2,q:'750 mL correspondem a:',a:['0,075 L','0,75 L','7,5 L','75 L'],c:1,e:'750 ÷ 1.000 = 0,75 L.'},
{id:30,s:'Matemática',t:'Sequências',d:1,q:'5, 10, 15, 20, __',a:['22','24','25','30'],c:2,e:'A sequência cresce de 5 em 5.'},
{id:31,s:'Matemática',t:'Sequências',d:3,q:'2, 5, 11, 23, __',a:['35','41','45','47'],c:3,e:'Cada termo = anterior × 2 + 1. 23 × 2 + 1 = 47.'},
{id:32,s:'Matemática',t:'Porcentagem',d:2,q:'25% de 80 é:',a:['10','15','20','25'],c:2,e:'25% = 1/4; 80 ÷ 4 = 20.'},
{id:33,s:'Matemática',t:'Porcentagem',d:3,q:'R$ 200 com 15% de desconto passa a custar:',a:['R$160','R$170','R$175','R$185'],c:1,e:'15% de 200 = 30; 200 - 30 = 170.'},
{id:34,s:'Matemática',t:'Problemas',d:1,q:'125 livros mais 87 livros totalizam:',a:['202','212','222','232'],c:1,e:'125 + 87 = 212.'},
{id:35,s:'Matemática',t:'Problemas',d:2,q:'96 canetas divididas igualmente em 8 grupos dão:',a:['10','11','12','13'],c:2,e:'96 ÷ 8 = 12.'},
{id:36,s:'Matemática',t:'Problemas',d:3,q:'R$ 38,50 + R$ 24,75 pagos com R$ 100 geram troco de:',a:['R$35,75','R$36,75','R$37,25','R$38,25'],c:1,e:'38,50 + 24,75 = 63,25; 100 - 63,25 = 36,75.'},
{id:37,s:'Matemática',t:'Tempo',d:1,q:'Quanto tempo há entre 8h15 e 10h?',a:['1h15','1h30','1h45','2h'],c:2,e:'De 8h15 até 10h são 1h45.'},
{id:38,s:'Matemática',t:'Tempo',d:3,q:'Um filme começou às 18h35 e durou 2h25. Terminou às:',a:['20h50','21h00','21h10','21h20'],c:1,e:'18h35 + 2h25 = 21h00.'},
{id:39,s:'Matemática',t:'Decimais',d:1,q:'Quanto é 7,8 - 2,3?',a:['5,3','5,5','5,7','6,5'],c:1,e:'7,8 - 2,3 = 5,5.'},
{id:40,s:'Matemática',t:'Raciocínio',d:3,q:'Se 6 máquinas produzem 48 peças, 9 máquinas, na mesma proporção, produzem:',a:['64','68','72','76'],c:2,e:'48 ÷ 6 = 8 peças por máquina; 9 × 8 = 72.'},
{id:41,s:'Português',t:'Ortografia',d:1,q:'Qual palavra está correta?',a:['enchergar','enxergar','encherguar','enxerguar'],c:1,e:'A forma correta é “enxergar”.'},
{id:42,s:'Português',t:'Ortografia',d:2,q:'Em qual opção todas estão corretas?',a:['viagem, jeito, coragem','viajem, geito, coragem','viagem, geito, corajem','viajem, jeito, corajem'],c:0,e:'“Viagem”, “jeito” e “coragem” estão corretas.'},
{id:43,s:'Português',t:'Acentuação',d:1,q:'Qual palavra deve receber acento?',a:['lapis','mesa','caderno','janela'],c:0,e:'A forma correta é “lápis”.'},
{id:44,s:'Português',t:'Acentuação',d:2,q:'Assinale a palavra corretamente acentuada.',a:['voce','tambem','fácil','juri'],c:2,e:'“Fácil” é paroxítona terminada em L.'},
{id:45,s:'Português',t:'Classes gramaticais',d:1,q:'Em “O cachorro correu”, “cachorro” é:',a:['verbo','substantivo','adjetivo','advérbio'],c:1,e:'“Cachorro” nomeia um ser; é substantivo.'},
{id:46,s:'Português',t:'Classes gramaticais',d:2,q:'Em “A prova estava difícil”, “difícil” é:',a:['adjetivo','verbo','pronome','artigo'],c:0,e:'“Difícil” caracteriza “prova”; é adjetivo.'},
{id:47,s:'Português',t:'Verbos',d:1,q:'Em “Eles viajaram ontem”, o verbo está no:',a:['presente','passado','futuro','infinitivo'],c:1,e:'“Viajaram” indica ação passada.'},
{id:48,s:'Português',t:'Verbos',d:2,q:'Qual frase tem verbo no futuro?',a:['Eu estudo agora.','Eu estudei ontem.','Eu estudarei amanhã.','Eu estudava cedo.'],c:2,e:'“Estudarei” indica futuro.'},
{id:49,s:'Português',t:'Pontuação',d:1,q:'Qual frase está corretamente pontuada?',a:['Pedro comprou pão leite e frutas.','Pedro comprou pão, leite e frutas.','Pedro, comprou pão leite e frutas.','Pedro comprou, pão leite e frutas.'],c:1,e:'A vírgula separa itens de uma enumeração.'},
{id:50,s:'Português',t:'Pontuação',d:3,q:'Qual vocativo está corretamente separado?',a:['Amigos vamos começar.','Amigos, vamos começar.','Amigos vamos, começar.','Amigos; vamos começar.'],c:1,e:'“Amigos” é vocativo e deve ser separado por vírgula.'},
{id:51,s:'Português',t:'Vocabulário',d:1,q:'“Generoso” é alguém que:',a:['compartilha e ajuda','fala pouco','tem medo','se atrasa'],c:0,e:'Generoso é quem ajuda ou compartilha.'},
{id:52,s:'Português',t:'Vocabulário',d:2,q:'Sinônimo de “rápido”:',a:['lento','veloz','pesado','calmo'],c:1,e:'“Veloz” tem sentido equivalente a “rápido”.'},
{id:53,s:'Português',t:'Interpretação',d:1,q:'“Lucas levou guarda-chuva porque o céu estava carregado.” Ele levou porque:',a:['estava calor','poderia chover','ia à praia','perdeu a mochila'],c:1,e:'Céu carregado é indício de chuva.'},
{id:54,s:'Português',t:'Interpretação',d:2,q:'“Marina treinou por semanas e finalmente completou a corrida.” A ideia principal é:',a:['ela desistiu','a persistência trouxe resultado','a corrida foi cancelada','ela não treinava'],c:1,e:'O texto relaciona persistência e conquista.'},
{id:55,s:'Português',t:'Interpretação',d:3,q:'“Embora estivesse cansado, Rafael terminou a tarefa.” “Embora” indica:',a:['causa','concessão/oposição','tempo','conclusão'],c:1,e:'“Embora” introduz concessão: mesmo cansado, terminou.'},
{id:56,s:'Português',t:'Pronomes',d:1,q:'Em “Ela trouxe o livro”, “ela” é:',a:['verbo','adjetivo','pronome','substantivo'],c:2,e:'“Ela” é pronome pessoal.'},
{id:57,s:'Português',t:'Pronomes',d:2,q:'Em “João viu Pedro e o chamou”, “o” refere-se a:',a:['João','Pedro','ninguém','viu'],c:1,e:'O pronome “o” retoma Pedro.'},
{id:58,s:'Português',t:'Concordância',d:1,q:'Assinale a frase correta.',a:['Os meninos brinca.','Os meninos brincam.','O meninos brincam.','Os menino brinca.'],c:1,e:'“Os meninos brincam” apresenta concordância adequada.'},
{id:59,s:'Português',t:'Concordância',d:3,q:'Qual frase está correta?',a:['As alunas dedicada estudaram.','As alunas dedicadas estudaram.','As aluna dedicadas estudou.','A alunas dedicada estudaram.'],c:1,e:'Artigo, substantivo, adjetivo e verbo concordam corretamente.'},
{id:60,s:'Português',t:'Coesão',d:2,q:'“Estava chovendo; _____, levamos guarda-chuva.”',a:['por isso','porém','embora','enquanto'],c:0,e:'“Por isso” introduz consequência.'}
];
let db={family:null};try{let x=JSON.parse(localStorage.getItem(STORE));if(x)db=x}catch(e){};let mode='parent',session=null,live=null,timer=null;
async function hash(t){let b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const norm=s=>(s||'').trim().toLowerCase(),day=()=>new Date().toLocaleDateString('en-CA'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem(STORE,JSON.stringify(db))}function ch(){return db.family.children.find(x=>x.id===session?.childId)}function fmt(s){if(s==null)return'—';s=Math.round(s);let m=Math.floor(s/60),r=s%60;return(m?m+'m ':'')+r+'s'}
function freshChild(name,login,passHash){return{id:'c'+Date.now()+Math.random().toString(36).slice(2,6),name,login,passHash,diagnostic:{completed:false},answers:[],sessions:[],rewards:REW.map(x=>({...x}))}}
function stats(c){let a=c.answers||[],n=a.length,o=a.filter(x=>x.ok).length,t=a.reduce((z,x)=>z+(x.sec||0),0);return{n,p:n?Math.round(o*100/n):null,av:n?Math.round(t/n):null}}function todayN(c){return(c.answers||[]).filter(x=>x.day===day()&&x.mode!=='diagnostico').length}
function level(score){return score>=75?'Avançado':score>=50?'Intermediário':'Inicial'}function show(id){document.querySelectorAll('.view').forEach(x=>x.classList.add('hide'));$(id).classList.remove('hide')}
function setMode(m){mode=m;$('parentMode').classList.toggle('on',m==='parent');$('childMode').classList.toggle('on',m==='child')}$('parentMode').onclick=()=>setMode('parent');$('childMode').onclick=()=>setMode('child');
$('openRegister').onclick=()=>{$('authView').classList.add('hide');$('registerView').classList.remove('hide')};$('backLogin').onclick=()=>{$('registerView').classList.add('hide');$('authView').classList.remove('hide')};
$('registerBtn').onclick=async()=>{let pn=$('rpName').value.trim(),pl=norm($('rpLogin').value),pp=$('rpPass').value,cn=$('rcName').value.trim(),cl=norm($('rcLogin').value),cp=$('rcPass').value;if(!pn||!pl||pp.length<4||!cn||!cl||cp.length<4){$('regMsg').innerHTML='<div class=bad>Preencha todos os campos. Senhas com no mínimo 4 caracteres.</div>';return}if(pl===cl){$('regMsg').innerHTML='<div class=bad>Os logins do responsável e do aluno precisam ser diferentes.</div>';return}db.family={parent:{name:pn,login:pl,passHash:await hash(pp)},children:[freshChild(cn,cl,await hash(cp))]};save();$('registerView').classList.add('hide');$('authView').classList.remove('hide');$('loginMsg').innerHTML='<div class=ok>Cadastro criado. Faça o login.</div>'};
$('loginBtn').onclick=async()=>{if(!db.family){$('loginMsg').innerHTML='<div class=bad>Crie o cadastro da família primeiro.</div>';return}let u=norm($('loginUser').value),p=await hash($('loginPass').value);if(mode==='parent'){if(u!==db.family.parent.login||p!==db.family.parent.passHash){$('loginMsg').innerHTML='<div class=bad>Login ou senha inválidos.</div>';return}session={role:'parent'};openParent()}else{let c=db.family.children.find(x=>x.login===u&&x.passHash===p);if(!c){$('loginMsg').innerHTML='<div class=bad>Login ou senha do aluno inválidos.</div>';return}session={role:'child',childId:c.id};openChild()}};
$('logoutBtn').onclick=()=>{clearInterval(timer);session=live=null;$('sessionInfo').classList.add('hide');$('mainNav').classList.add('hide');document.querySelectorAll('.view').forEach(x=>x.classList.add('hide'));$('authView').classList.remove('hide');$('loginPass').value=''};
function badge(t){$('sessionBadge').textContent=t;$('sessionInfo').classList.remove('hide')}
function openParent(){$('authView').classList.add('hide');badge('RESPONSÁVEL • '+db.family.parent.name);$('mainNav').innerHTML='<button>⚙️ Administração</button>';$('mainNav').classList.remove('hide');show('parentView');renderParent()}
function openChild(){$('authView').classList.add('hide');badge('ALUNO • '+ch().name);navChild();if(!ch().diagnostic.completed){show('diagnosticView');renderDiagGate()}else{show('childHome');renderHome()}}
function navChild(){let c=ch();$('mainNav').innerHTML=c.diagnostic.completed?'<button data-v="childHome">🏠 Início</button><button data-v="exerciseView">🎯 Exercícios</button><button data-v="reviewView">🧠 Revisão</button><button data-v="rewardView">🏆 Premiações</button>':'<button data-v="diagnosticView">🧭 Diagnóstico</button>';$('mainNav').classList.remove('hide');$('mainNav').querySelectorAll('button').forEach(b=>b.onclick=()=>{show(b.dataset.v);if(b.dataset.v==='childHome')renderHome();if(b.dataset.v==='diagnosticView')renderDiagGate();if(b.dataset.v==='exerciseView')renderExerciseGate();if(b.dataset.v==='rewardView')renderRewards()})}
function renderParent(){$('parentHello').textContent='Olá, '+db.family.parent.name;$('childrenList').innerHTML=db.family.children.map(c=>{let s=stats(c),d=c.diagnostic||{};return`<div class=child><div class=childtop><div><b style="font-size:19px">${esc(c.name)}</b><div class=mut>Login: <b>${esc(c.login)}</b></div></div><span class=pill>${d.completed?d.level+' • '+d.score+'%':'Diagnóstico pendente'}</span></div><div class=row style="margin-top:10px"><span class=pill>${s.n} respostas</span><span class=pill>${s.p==null?'—':s.p+'%'} de acerto</span><span class=pill>${todayN(c)} hoje</span></div><div class=row style="margin-top:12px"><button class="btn btn2" onclick="changePass('${c.id}')">Alterar senha</button><button class="btn btn2" onclick="editRewards('${c.id}')">Premiações</button>${d.completed?`<button class="btn danger" onclick="resetDiag('${c.id}')">Resetar diagnóstico</button>`:''}</div></div>`}).join('')}
$('addChildBtn').onclick=async()=>{let n=prompt('Nome do aluno:');if(!n)return;let l=norm(prompt('Login do aluno:')||'');if(!l)return;if(l===db.family.parent.login||db.family.children.some(x=>x.login===l)){alert('Login já em uso.');return}let p=prompt('Senha do aluno (mínimo 4 caracteres):')||'';if(p.length<4)return alert('Senha muito curta.');db.family.children.push(freshChild(n.trim(),l,await hash(p)));save();renderParent()};
window.changePass=async id=>{let c=db.family.children.find(x=>x.id===id),p=prompt('Nova senha para '+c.name+':')||'';if(p.length<4)return;c.passHash=await hash(p);save();alert('Senha atualizada.')};
window.editRewards=id=>{let c=db.family.children.find(x=>x.id===id);c.rewards.forEach((r,i)=>{let n=prompt('Meta '+(i+1)+' - quantidade de questões:',r.n);let name=prompt('Prêmio da meta '+(i+1)+':',r.name);if(n)r.n=Math.max(1,parseInt(n)||r.n);if(name)r.name=name.trim()||r.name});c.rewards.sort((a,b)=>a.n-b.n);save();alert('Premiações atualizadas.')};
window.resetDiag=id=>{let c=db.family.children.find(x=>x.id===id);if(!confirm('Resetar o diagnóstico de '+c.name+'? No próximo acesso o teste será obrigatório novamente.'))return;c.diagnostic={completed:false};c.answers=c.answers.filter(x=>x.mode!=='diagnostico');c.sessions=c.sessions.filter(x=>x.mode!=='diagnostico');save();renderParent()};
function renderHome(){let c=ch(),s=stats(c),d=c.diagnostic;$('childHello').textContent='Olá, '+c.name+' 👋';$('level').textContent=d.level+' • '+d.score+'%';$('today').textContent=todayN(c);$('accuracy').textContent=s.p==null?'—':s.p+'%';$('avgTime').textContent=fmt(s.av);let entries=Object.entries(d.subject||{}).sort((a,b)=>a[1]-b[1]);$('childStatus').innerHTML=`<div class=ok><b>Diagnóstico concluído.</b> Os exercícios estão ajustados ao nível <b>${d.level}</b>.</div>${entries.length?`<p class=mut>Área inicial de maior atenção: <b>${entries[0][0]} (${entries[0][1]}%)</b>.</p>`:''}`;let n=todayN(c),next=c.rewards.find(r=>n<r.n),done=[...c.rewards].reverse().find(r=>n>=r.n);$('nextReward').innerHTML=done?`<div class=ok><b>🏆 Conquistado: ${done.emoji} ${esc(done.name)}</b></div>`:next?`<div class=note><b>Próxima recompensa: ${next.emoji} ${esc(next.name)}</b><br>Faltam ${next.n-n} questões.</div>`:''}
function renderDiagGate(){let c=ch();$('diagArea').innerHTML=c.diagnostic.completed?`<div class=ok><b>Diagnóstico já concluído.</b><br>Nível ${c.diagnostic.level} • ${c.diagnostic.score}%.</div>`:'';$('startDiag').classList.toggle('hide',c.diagnostic.completed)}$('startDiag').onclick=()=>startSession('diagnostico');
function renderExerciseGate(){let c=ch();if(!c.diagnostic.completed){show('diagnosticView');renderDiagGate();return}$('exerciseIntro').innerHTML=`Nível identificado: <b>${c.diagnostic.level}</b>. A seleção considera dificuldade, pontos fracos e questões já vistas.`;$('exerciseArea').innerHTML=''}$('startExercise').onclick=()=>startSession('exercicio');$('startReview').onclick=()=>startSession('revisao');
function choose(m){let c=ch();if(m==='diagnostico')return Q.filter(q=>q.g);let pool=Q.filter(q=>!q.g),seen=new Set(c.answers.filter(x=>x.mode!=='diagnostico').map(x=>x.qid)),recent=new Set(c.answers.slice(-20).map(x=>x.qid)),wrong=new Set(c.answers.filter(x=>!x.ok).map(x=>x.qid)),weak=Object.entries(c.diagnostic.subject||{}).sort((a,b)=>a[1]-b[1]).map(x=>x[0]),target=c.diagnostic.level==='Inicial'?1:c.diagnostic.level==='Intermediário'?2:3;if(m==='revisao'){let arr=pool.map(q=>({q,sc:(wrong.has(q.id)?100:0)+(weak[0]===q.s?35:0)+(recent.has(q.id)?-80:0)+Math.random()*10})).sort((a,b)=>b.sc-a.sc);return arr.slice(0,10).map(x=>x.q)}return pool.map(q=>({q,sc:(!seen.has(q.id)?130:-60)+(recent.has(q.id)?-120:0)+(q.d===target?40:Math.abs(q.d-target)===1?12:0)+(weak[0]===q.s?20:0)+Math.random()*10})).sort((a,b)=>b.sc-a.sc).slice(0,10).map(x=>x.q)}
function startSession(m){live={mode:m,qs:choose(m),answers:{},start:Date.now()};renderLive()}
function renderLive(){let box=live.mode==='diagnostico'?$('diagArea'):live.mode==='revisao'?$('reviewArea'):$('exerciseArea'),title=live.mode==='diagnostico'?'Diagnóstico':live.mode==='revisao'?'Revisão':'Exercícios',n=live.qs.length;box.innerHTML=`<div class="sticky bar"><div><b>${title} • ${n} questões</b><div class=mut><span id=answered>0</span>/${n} respondidas</div></div><div><div class=mut>Tempo</div><div id=clock class=timer>0s</div></div></div>`+live.qs.map((q,i)=>`<div class=question><div class=mut>${q.s} • ${q.t} • nível ${q.d}</div><h3>${i+1}. ${q.q}</h3><div class=answers>${q.a.map((a,j)=>`<label class=opt data-q="${i}" data-a="${j}"><input type=radio name="q${i}"><span><b>${String.fromCharCode(65+j)})</b> ${a}</span></label>`).join('')}</div></div>`).join('')+'<button id=finish class=btn>Entregar respostas</button>';box.querySelectorAll('.opt').forEach(el=>el.onclick=()=>{let i=+el.dataset.q,j=+el.dataset.a;live.answers[i]=j;el.closest('.answers').querySelectorAll('.opt').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');$('answered').textContent=Object.keys(live.answers).length});$('finish').onclick=finish;clearInterval(timer);timer=setInterval(()=>{if($('clock'))$('clock').textContent=fmt((Date.now()-live.start)/1000)},1000)}
function finish(){let n=live.qs.length;if(Object.keys(live.answers).length<n&&!confirm('Há questões sem resposta. Entregar assim mesmo?'))return;clearInterval(timer);let c=ch(),sec=Math.max(1,Math.round((Date.now()-live.start)/1000)),per=Math.round(sec/n),ok=0,res=[];live.qs.forEach((q,i)=>{let sel=live.answers[i],hit=sel===q.c;if(hit)ok++;res.push({q,sel,hit});c.answers.push({qid:q.id,s:q.s,t:q.t,d:q.d,ok:hit,mode:live.mode,day:day(),sec:per,ts:Date.now()})});let score=Math.round(ok*100/n);c.sessions.push({mode:live.mode,day:day(),score,totalSec:sec,avgSec:per});if(live.mode==='diagnostico'){let subject={};['Matemática','Português'].forEach(s=>{let a=res.filter(x=>x.q.s===s);subject[s]=Math.round(a.filter(x=>x.hit).length*100/a.length)});c.diagnostic={completed:true,score,level:level(score),date:day(),subject}}save();let box=live.mode==='diagnostico'?$('diagArea'):live.mode==='revisao'?$('reviewArea'):$('exerciseArea');box.innerHTML=`<div class=${score>=70?'ok':'note'}><b>${live.mode==='diagnostico'?'Diagnóstico':'Sessão'}: ${ok}/${n} (${score}%).</b><br>Tempo: ${fmt(sec)} • média ${fmt(per)} por questão.${live.mode==='diagnostico'?`<br><b>Nível identificado: ${c.diagnostic.level}</b>`:''}</div><h3>Correção comentada</h3>`+res.map((r,i)=>`<div class="review ${r.hit?'correct':'wrong'}"><div class=mut>${r.q.s} • ${r.q.t}</div><h3>${i+1}. ${r.q.q}</h3><div class=${r.hit?'ok':'bad'}><b>${r.hit?'✅ Acertou':'❌ Errou'}</b><br>Sua resposta: ${r.sel==null?'Não respondida':String.fromCharCode(65+r.sel)+') '+r.q.a[r.sel]}${r.hit?'':`<br>Correta: ${String.fromCharCode(65+r.q.c)}) ${r.q.a[r.q.c]}`}</div><div class=comment><b>Comentário:</b> ${r.q.e}</div></div>`).join('')+(live.mode==='diagnostico'?'<button id=goHome class=btn>Ir para meu painel</button>':'');live=null;navChild();if($('goHome'))$('goHome').onclick=()=>{show('childHome');renderHome()}}
function renderRewards(){let c=ch(),n=todayN(c),mx=Math.max(...c.rewards.map(r=>r.n));$('rewardTitle').textContent='Recompensas de '+c.name;$('rewardToday').textContent=n;$('rewardBar').style.width=Math.min(100,n/mx*100)+'%';$('rewardList').innerHTML=c.rewards.map(r=>`<div class="reward ${n>=r.n?'done':''}"><div><b>${r.emoji} ${esc(r.name)}</b><div class=mut>${r.n} questões no dia</div></div><b>${n>=r.n?'CONQUISTADO':'Faltam '+(r.n-n)}</b></div>`).join('')}
